version: '3.8'

services:
  # Backend API (Go)
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./data:/root/data
      - ./logs:/root/logs
      - ./config.prod.yaml:/root/config.yaml
    environment:
      - LOG_LEVEL=info
      - LOG_FORMAT=json
      - LOG_OUTPUT_PATH=logs/app.log
      - ML_SERVICE_URL=http://ml-service:8000
    depends_on:
      - ml-service
    networks:
      - reviews-network
    restart: unless-stopped

  # ML Service (Python FastAPI) - FIXED MODEL (banking_topics_mlflow_light)
  ml-service:
    build:
      context: ../../ml_service
      dockerfile: Dockerfile
    networks:
      - reviews-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

networks:
  reviews-network:
    driver: bridge